huh_amp:
  templates:
    ce_text:
      amp_template: true
    ce_html:
      amp_template: true
    ce_accordionSingle:
      components: ['accordion']
    ce_accordionStart:
      components: ['accordion']
    ce_accordionStop:
      components: ['accordion']
    ce_image: ~
    image.html.twig: ~
    ce_player: ~
    ce_slick:
      components: ['carousel']
    ce_youtube:
      components: ['youtube']
    ce_youtube_huh:
      components: ['youtube']
    mod_block:
      amp_template: true
    mod_reader:
      amp_template: true
    mod_customnav:
      components: ['accordion']
    mod_navigation:
      components: ['sidebar','accordion']
    mod_ampnavigation:
      components: ['sidebar','accordion']
      amp_template: true
    mod_customnav_amp:
      components: ['accordion']
    slick_default: ~
    nav_default: ~
    cookiebar: ~
  components:
    accordion: { url: "https://cdn.ampproject.org/v0/amp-accordion-0.1.js" }
    analytics: { url: "https://cdn.ampproject.org/v0/amp-analytics-0.1.js" }
    audio:     { url: "https://cdn.ampproject.org/v0/amp-audio-0.1.js" }
    carousel:  { url: "https://cdn.ampproject.org/v0/amp-carousel-0.1.js" }
    sidebar:   { url: "https://cdn.ampproject.org/v0/amp-sidebar-0.1.js" }
    video:     { url: "https://cdn.ampproject.org/v0/amp-video-0.1.js" }
    youtube:   { url: "https://cdn.ampproject.org/v0/amp-youtube-0.1.js" }
    form:      { url: "https://cdn.ampproject.org/v0/amp-form-0.1.js" }