services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - ["setContainer", ["@service_container"]]
  huh.amp.manager.data_container.page:
    class: HeimrichHannot\AmpBundle\DataContainer\PageContainer
    public: true
    autowire: true