services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
      - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
      - ["setContainer", ["@service_container"]]

  huh.amp.event_listener.hook_listener:
    class: HeimrichHannot\AmpBundle\EventListener\HookListener
    public: true
    autowire: true
  HeimrichHannot\AmpBundle\EventListener\RenderTwigTemplateListener:
    tags:
      - { name: kernel.event_listener, event: huh.utils.template.render, method: onRenderTemplate }