services:
  _defaults:
    autowire: true

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
      - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
      - ["setContainer", ["@service_container"]]

  huh.amp.event_listener.hook_listener:
    class: HeimrichHannot\AmpBundle\EventListener\HookListener
    public: true

  HeimrichHannot\AmpBundle\EventListener\RenderTwigTemplateListener:
    tags:
      - { name: kernel.event_listener, event: huh.utils.template.render, method: onRenderTemplate }
  HeimrichHannot\AmpBundle\EventListener\PrepareAmpTemplateListener:
    tags:
      - { name: kernel.event_listener, event: huh.amp.event.prepare_amp_template }

  HeimrichHannot\AmpBundle\EventListener\GeneratePageListener:
    public: true