services:
  _defaults:
    autowire: true
    public: true

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
      - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
      - ["setContainer", ["@service_container"]]

  huh.amp.event_listener.hook_listener:
    class: HeimrichHannot\AmpBundle\EventListener\HookListener

  HeimrichHannot\AmpBundle\EventListener\PrepareAmpTemplateListener:
    public: false
    tags:
      - { name: kernel.event_listener, event: huh.amp.event.prepare_amp_template }