services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
      - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
      - ["setContainer", ["@service_container"]]

  huh.amp.event_listener.hook_listener:
    class: HeimrichHannot\AmpBundle\EventListener\HookListener
    public: true
    autowire: true

  huh.amp.manager.amp_manager:
    class: HeimrichHannot\AmpBundle\Manager\AmpManager
    public: true
    autowire: true

  huh.amp.util.amp_util:
    class: HeimrichHannot\AmpBundle\Util\AmpUtil
    public: true
    autowire: true