services:
  _defaults:
    public: true
    autowire: true
    bind:
      $ampBundleConfig: '%huh_amp%'

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
      - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
      - ["setContainer", ["@service_container"]]

  HeimrichHannot\AmpBundle\EventListener\Contao\:
    resource: '../../EventListener/Contao/*'
    public: false
    autowire: true
    autoconfigure: true


  HeimrichHannot\AmpBundle\Manager\AmpManager: ~
  huh.amp.manager.amp_manager: '@HeimrichHannot\AmpBundle\Manager\AmpManager'

  HeimrichHannot\AmpBundle\Util\AmpUtil: ~
  huh.amp.util.amp_util: '@HeimrichHannot\AmpBundle\Util\AmpUtil'

  huh.amp.util.layout_util:
    class: HeimrichHannot\AmpBundle\Util\LayoutUtil
    public: true
    autowire: true

  huh.head.tag.link_amp:
    class: HeimrichHannot\AmpBundle\Tag\Link\LinkAmp
    arguments: ['@huh.head.tag_manager']
    public: true