services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
      - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
      - ["setContainer", ["@service_container"]]

  huh.amp.manager.amp_manager:
    class: HeimrichHannot\AmpBundle\Manager\AmpManager
    public: true
    autowire: true

  huh.amp.util.amp_util:
    class: HeimrichHannot\AmpBundle\Util\AmpUtil
    public: true
    autowire: true

  huh.amp.util.layout_util:
    class: HeimrichHannot\AmpBundle\Util\LayoutUtil
    public: true
    autowire: true

  huh.head.tag.link_amp:
    class: HeimrichHannot\AmpBundle\Tag\Link\LinkAmp
    arguments: ['@huh.head.tag_manager']
    public: true